name: WinxxAntiGriefing
version: '${project.version}'
main: net.winxxdeveloper.winxxantigriefing.Terminal
authors: [ LeticiaCHEAT ]
description: Plugin de antigriefing integrado ao discord - FREE
commands:
  antigriefing:
    aliases: [ag]